# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Twilio SendGrid Email
      # You may pin to the exact commit or the version.
      # uses: mmeisels/actions-email@d7f08371c7aec87c57e05171100652c4e17a41e3
      uses: mmeisels/actions-email@v1.1
        with:
          # Email To Address
          emailToAddress: 
          # Email From Address
          emailFromAddress: 
          # The email body you want to send
          emailBody: 
          # The SendGrid Email Template ID
          emailTemplateID: # optional
          # The SendGrid API Key using to authenticate with
          SENDGRID_API_KEY: 
          # The SendGrid Unsubscribe Group ID
          unSubscribeGroupID: # optional
